S' : program

program : stmt
program : program stmt 

stmt : expr 

expr : NUMBER
expr : STRING
expr : BOOL
expr : ID
expr : E
expr : PI
expr : LPAREN expr RPAREN
expr : SUB expr
expr : NOT expr
expr : expr ADD expr
expr : expr SUB expr
expr : expr MUL expr
expr : expr DIV expr
expr : expr MOD expr
expr : expr POW expr
expr : expr CONCAT expr
expr : expr CONCAT_SPACE expr
expr : expr LT expr
expr : expr GT expr
expr : expr LE expr
expr : expr GE expr
expr : expr EQ expr
expr : expr NE expr
expr : expr AND expr
expr : expr OR expr
expr : SIN LPAREN expr RPAREN
expr : COS LPAREN expr RPAREN
expr : MIN LPAREN expr COMMA expr RPAREN
expr : MAX LPAREN expr COMMA expr RPAREN
expr : SQRT LPAREN expr RPAREN
expr : LOG LPAREN expr COMMA expr RPAREN
expr : EXP LPAREN expr RPAREN
expr : RANDOM LPAREN RPAREN